version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ['/bin/bash', '-c', 'yarn && yarn run start:dev']
    environment:
      - LANG=fr_FR.utf8
      - TZ=Europe/Paris
